BU:
  a: sa
  a_dim: null
  a_ffdim: null
  a_layers: 1
  a_nhead: 8
  dropout: null
  f: null
  f_dim: null
  f_layers: 10
  f_ln: null
  f_ngp: null
  hid_dim: null
  s_layers: 1
Bi:
  a: sca
  a_dim: 256
  a_ffdim: 512
  a_layers: 6
  a_nhead: 8
  dropout: 0.0
  f: m2
  f_dim: 256
  f_layers: 10
  f_ln: false
  f_ngp: 1
  hid_dim: 512
Bu:
  a: sa
  a_dim: null
  a_ffdim: null
  a_layers: 1
  a_nhead: 8
  dropout: null
  f: null
  f_dim: null
  f_layers: 10
  f_ln: null
  f_ngp: null
  hid_dim: null
FACT:
  block: iUUU
  cmr: 0.3
  fpos: false
  ntoken: 200
  trans: false
  mwt: 0.9
Loss:
  a2fc: 1.0
  bgw: 0.5
  match: o2o
  nullw: -1.0
  pc: 0.2
  sw: 5.0
TM:
  inplace: true
  m: 5
  p: 0.05
  t: 30
  use: false
aux:
  debug: false
  eval_every: 10000
  gpu: 0
  mark: ""
  print_every: 4000
  resume: max
  runid: 0
batch_size: 1
clip_grad_norm: 10.0
dataset: ego
eval_bg: false
epoch: 350
lr: 0.0001
lr_decay: 250
momentum: 0.0
optimizer: Adam
split: split1
sr: 3
weight_decay: 0.0
