BU:
  a: sa
  a_dim: null
  a_ffdim: null
  a_layers: 1
  a_nhead: 8
  dropout: null
  f: null
  f_dim: null
  f_layers: 10
  f_ln: null
  f_ngp: null
  hid_dim: null
  s_layers: 1
Bi:
  a: sca
  a_dim: 128
  a_ffdim: 512
  a_layers: 6
  a_nhead: 8
  dropout: 0.2
  f: m
  f_dim: 128
  f_layers: 10
  f_ln: false
  f_ngp: 1
  hid_dim: 512
Bu:
  a: sa
  a_dim: null
  a_ffdim: null
  a_layers: 1
  a_nhead: 8
  dropout: null
  f: null
  f_dim: null
  f_layers: 10
  f_ln: null
  f_ngp: null
  hid_dim: null
FACT:
  block: iuU
  cmr: 0.5
  fpos: false
  ntoken: 60
  trans: false
  mwt: 0.1
Loss:
  a2fc: 1.0
  bgw: 1.0
  match: o2o
  nullw: -1.0
  pc: 0.2
  sw: 5.0
TM:
  inplace: true
  m: 5
  p: 0.1
  t: 60
  use: true
aux:
  debug: false
  eval_every: 300
  gpu: 5
  mark: ""
  print_every: 100
  resume: max
  runid: 1
batch_size: 1
clip_grad_norm: 10.0
dataset: gtea
eval_bg: false
epoch: 400
lr: 0.0001
lr_decay: 250
momentum: 0.0
optimizer: Adam
split: split1
sr: 1
weight_decay: 0.0
