BU:
  a: sa
  a_dim: None
  a_ffdim: None
  a_layers: 1
  a_nhead: 8
  dropout: None
  f: None
  f_dim: None
  f_layers: 5
  f_ln: None
  f_ngp: None
  hid_dim: None
  s_layers: 1
Bi:
  a: sca
  a_dim: 128
  a_ffdim: 512
  a_layers: 3
  a_nhead: 8
  dropout: 0.2
  f: m
  f_dim: 128
  f_layers: 10
  f_ln: false
  f_ngp: 1
  hid_dim: 512
Bu:
  a: sa
  a_dim: None
  a_ffdim: None
  a_layers: 1
  a_nhead: 8
  dropout: None
  f: None
  f_dim: None
  f_layers: 3
  f_ln: None
  f_ngp: None
  hid_dim: None
FACT:
  block: iuU
  cmr: 0.5
  fpos: false
  mwt: 0.0
  ntoken: 0
  trans: true
Loss:
  a2fc: 1.0
  bgw: 1.0
  match: seq
  nullw: -1.0
  pc: 1.0
  sw: 5.0
TM:
  inplace: true
  m: 5
  p: 0.1
  t: 60
  use: true
aux:
  debug: false
  eval_every: 900
  gpu: 0
  mark: ''
  print_every: 400
  resume: max
  runid: 8
batch_size: 1
clip_grad_norm: 10.0
dataset: gtea
epoch: 2000
eval_bg: False
lr: 0.0001
lr_decay: -1
momentum: 0.0
optimizer: Adam
split: split4
sr: 1
weight_decay: 0.0
